image: Visual Studio 2017

init:
  - cmd: set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

install:
  - cmd: pip install -r requirements.txt

build_script:
  - cmd: python -m fbs freeze --debug

test: off

artifacts:
  - path: target/Calibra
    type: zip
